### PR TITLE
Feature/inline images

### PR DESCRIPTION
**Pull request by oniboni**
Solves #8 

**NOTE:** This feature is built on top of #7

### CODE REVIEW

**Comment by b-bittner** [comment]
Again, thank you very much for this PR!
Unfortunately, this one does not work, at least in my lab.
When enabling the InlineImages feature, I just get the markdown version of the kroki-code.
I've tried to troubleshoot it a little bit, but I do not fully understand how it should work.

I believe the function `on_page_content` looks into the html to find the kroki part in a code-tag with kroki-parameters.
But in my lab there are no html-tag-parameters indicating kroki-code, so nothing can be found

Not sure how to describe it better, how can I help with the troubleshooting?

**Comment by oniboni** [comment]
Yes, it should work the way you are describing it.

Code blocks are normally put into the html inside of code tags with a class describing the language, eg:
```html
<pre>
    <code class="language-excalidraw">[raw diagram text]
    </code>
</pre>
```
The class name may depend on the mkdocs version. It seems, that older versions did not add the prefix `language-` to it.
(I tested on `mkdocs, version 1.2.3`, `Python 3.9`(gentoo) and `Python 3.10`(ubuntu))

Maybe you could provide a minimal mkdocs setup, where it does not work? Then I could troubleshoot as well :)

**Comment by b-bittner** [comment]
I've updated all my packages in my virtual environment, but still, no rendering - html code classes are not added.

My dev environment uses Python 3.10.4 and mkdocs version 1.3.0.
Any ideas what could be wrong? Do I need an additional package?

**Comment by b-bittner** [comment]
any update on this? I can't get it up and running in my environment...

**Pull request closed without merging**
