### PR TITLE
Allow to render diagrams from file

### PR DESCRIPTION
**Pull request by tsouvarev**
I want to render really big diagrams (BPMN, which is XML), so it's handy to put diagram code in separate file and link it from docs.

### CODE REVIEW

**Comment by b-bittner** [comment]
Hello @tsouvarev ,
thanks for your PR, I appreciate your effort and looking forward to integrate your extension.
It would be helpful for the users if the is something for troubleshooting/logging, when the file does not exists.
Could you please add some logging and maybe also some hint which will be rendered into to docs.

**Comment by tsouvarev** [comment]
Sure, that makes sense. I will look into it.19 авг. 2022 г. 15:30 пользователь Benjamin Bittner ***@***.***> написал:
Hello @tsouvarev ,
thanks for your PR, I appreciate your effort and looking forward to integrate your extension.
It would be helpful for the users if the is something for troubleshooting/logging, when the file does not exists.
Could you please add some logging and maybe also some hint which will be rendered into to docs.

**Comment by tsouvarev** [comment]
I've added info message before reading file and error if operation didn't succeed

**Comment by b-bittner** [comment]
Hello @tsouvarev ,
sorry for the long silence, the last month were no time left for any other stuff than daily business.
Thanks for your added changes, looks much better now. One more thing I would like you to add before I can merge the PR:
Please add the mkdocs-parameter 'docs_dir' as base-path for the file-picking and also include this part of the path in the log message. I would guess, this would help others to find the problem when the plugin can't find the file.

**Comment by tsouvarev** [comment]
@b-bittner thanks for your time and valuable comment! fixed that

**Pull request merged**
